name: Deploy Staging

env:
  ENVIRONMENT: 'staging'
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches:
      - staging
      - staging-*
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: staging-release-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  docker-build-staging:
    name: Build Staging Image
    runs-on: ubuntu-latest
    environment:
      name: 'staging'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build staging image
        uses: ./.github/actions/build-docker-image
        with:
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          docker_image: ${{ env.IMAGE_NAME }}
          docker_tag: ${{ env.ENVIRONMENT }}
          next_private_telemetry_key: ${{ secrets.NEXT_PRIVATE_TELEMETRY_KEY }}
          next_private_telemetry_host: ${{ secrets.NEXT_PRIVATE_TELEMETRY_HOST }}
